name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>artifactory-repo</id><username>poorkende@gmail.com</username><password>Konyvtar2024</password></server></servers></settings>" > $C:\Users\MSI\Downloads\konyvek_beadando\settings.xml

      - name: Build with Maven and deploy artifact
        run: |
          mvn clean deploy
